### ISSUE TITLE
Try to fix special-casing for send-only transactions

### ISSUE THREAD

**Issue by voltrevo** [jzaki/bls-wallet-contracts#34]
Discussed this morning.

Unifying it with regular transactions would simplify things in several places and also enable aggregation for send-only transactions.

This is related to the separation between `methodId` and `encodedParams`.

If we could combine these then an empty array would naturally and securely signify a send-only operation, but currently `methodId` must be present, and if we had zeros here then someone could make a contract where that collides with a real call.

Combining these fields is tricky because they need to be separated in code and this can cause the local variables limit to be exceeded.

**Comment by jzaki** [comment]
Prior consideration on the .ts side, needs to be updated https://github.com/jzaki/bls-wallet-contracts/blob/main/shared/helpers/dataPayload.ts#L7
